name: AuctionHouse
version: '1.4.4'
main: me.elaineqheart.auctionHouse.AuctionHouse
api-version: '1.21'
authors: [ ElaineQheart, Corøna ]
website: https://www.youtube.com/@elaineqheart
depend: [ Vault ]
softdepend: [ PlaceholderAPI, Locale-API ]
permissions:
  auctionhouse.ah:
    description: allows the player to use /ah, /ah sell, /ah bid, etc.
    default: true
  auctionhouse.moderator:
    description: allows the player to use admin /ah commands (ban, delete, list, etc.)
    default: false


